export const BASE_STYLES = [
  ":root{--tk-crema:#F4F0E6;--tk-crema-deep:#EAE3D2;--tk-tinta:#1E2A23;--tk-tinta-soft:#2C3A31;--tk-noche:#131A16;--tk-humo:#8A8578;--tk-ceniza:#5A554A;--tk-cobre:#B4552D;--tk-cobre-light:#C96A42;--tk-cobre-dark:#8F4020;--tk-wa:#25D366;--font-serif:var(--font-fraunces);--font-sans:var(--font-archivo);--tk-ease:cubic-bezier(.22,1,.36,1)}",
  "*{box-sizing:border-box}",
  "html{scroll-behavior:smooth;scroll-padding-top:5rem}",
  "body{margin:0;background:var(--tk-crema);color:var(--tk-tinta);font-family:var(--font-archivo),system-ui,sans-serif;-webkit-font-smoothing:antialiased}",
  "a{color:inherit;text-decoration:none}",
  "button,input,select,textarea{font:inherit}",
  "button{color:inherit}",
  "img{display:block;max-width:100%}",
  "::selection{background:rgba(180,85,45,.25);color:var(--tk-tinta)}",
  ":where(a,button,input,select,textarea,summary,[tabindex]):focus-visible{outline:2px solid var(--tk-cobre);outline-offset:4px}",
  ".tk-sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}",
  ".tk-link-draw{background-image:linear-gradient(currentColor,currentColor);background-repeat:no-repeat;background-position:0 100%;background-size:0 1.5px;transition:background-size .5s var(--tk-ease)}",
  ".tk-link-draw:hover{background-size:100% 1.5px}",
  "@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*,*::before,*::after{animation-duration:.001ms!important;animation-iteration-count:1!important;scroll-behavior:auto!important;transition-delay:0ms!important;transition-duration:.001ms!important}}",
  "@media(prefers-contrast:more){.tk-muted{color:var(--tk-tinta)!important}.tk-muted-on-dark{color:var(--tk-crema)!important}.tk-link-draw{background-size:100% 2px}}",
].join("")
