export const EDITORIAL_STYLES = [
  ".tk-page{min-height:100vh}",
  ".tk-editorial-main{width:100%;max-width:816px;margin:0 auto;padding:8rem 1.25rem 6rem}",
  ".tk-article-main{width:100%;max-width:720px;margin:0 auto;padding:8rem 1.25rem 6rem}",
  ".tk-editorial-header{margin-bottom:3.5rem}",
  ".tk-editorial-eyebrow{margin:0;color:var(--tk-cobre-dark);font-family:var(--font-plex-mono),ui-monospace,monospace;font-size:11px;text-transform:uppercase;letter-spacing:.25em}",
  ".tk-editorial-title{margin:1rem 0 0;color:var(--tk-tinta);font-family:var(--font-fraunces),Georgia,serif;font-size:clamp(2.5rem,7vw,3rem);font-weight:600;line-height:1.12}",
  ".tk-editorial-title em{color:var(--tk-cobre);font-style:italic}",
  ".tk-editorial-intro{max-width:640px;margin:1.25rem 0 0;color:var(--tk-ceniza);font-size:16px;line-height:1.7}",
  ".tk-editorial-date{margin:1rem 0 0;color:var(--tk-ceniza);font-family:var(--font-plex-mono),ui-monospace,monospace;font-size:12px;letter-spacing:.04em}",
  ".tk-blog-list{display:flex;flex-direction:column;gap:1.25rem}",
  ".tk-blog-card{display:block;padding:1.75rem;border:1px solid rgba(30,42,35,.12);border-radius:.75rem;background:var(--tk-crema-deep);transition:border-color .3s var(--tk-ease),transform .3s var(--tk-ease)}",
  ".tk-blog-card:hover{border-color:rgba(180,85,45,.55);transform:translateY(-2px)}",
  ".tk-blog-card-meta,.tk-article-meta{margin:0;color:var(--tk-ceniza);font-family:var(--font-plex-mono),ui-monospace,monospace;font-size:11px;text-transform:uppercase;letter-spacing:.15em}",
  ".tk-blog-card-title{margin:.75rem 0 0;color:var(--tk-tinta);font-family:var(--font-fraunces),Georgia,serif;font-size:clamp(1.5rem,5vw,1.625rem);font-weight:600;line-height:1.25}",
  ".tk-blog-card-description{margin:.75rem 0 0;color:var(--tk-ceniza);font-size:14.5px;line-height:1.65}",
  ".tk-blog-card-link{display:inline-block;margin-top:1.25rem;color:var(--tk-cobre-dark);font-size:13.5px;font-weight:600}",
  ".tk-article-back{display:inline-block;color:var(--tk-cobre-dark);font-family:var(--font-plex-mono),ui-monospace,monospace;font-size:11.5px;text-transform:uppercase;letter-spacing:.18em}",
  ".tk-article-meta{margin-top:2rem}",
  ".tk-article-title{margin:1rem 0 0;color:var(--tk-tinta);font-family:var(--font-fraunces),Georgia,serif;font-size:clamp(2.5rem,8vw,3rem);font-weight:600;line-height:1.12}",
  ".tk-article-description{margin:1.5rem 0 0;padding-bottom:2.25rem;border-bottom:1px solid rgba(30,42,35,.15);color:var(--tk-ceniza);font-size:17px;line-height:1.7}",
  ".tk-article-sections{display:flex;flex-direction:column;gap:2.25rem;margin-top:2.5rem}",
  ".tk-article-section-title{margin:0 0 1rem;color:var(--tk-tinta);font-family:var(--font-fraunces),Georgia,serif;font-size:1.5rem;font-weight:600;line-height:1.3}",
  ".tk-article-body{margin:0;color:var(--tk-ceniza);font-size:16px;line-height:1.9}",
  ".tk-article-price-wrap{margin-top:1.5rem;overflow:hidden;border:1px solid rgba(30,42,35,.15);border-radius:.5rem}",
  ".tk-article-price-table{width:100%;border-collapse:collapse;text-align:left}",
  ".tk-article-price-table thead{background:var(--tk-tinta);color:var(--tk-crema)}",
  ".tk-article-price-table th,.tk-article-price-table td{padding:.875rem 1.25rem}",
  ".tk-article-price-table thead th{font-family:var(--font-plex-mono),ui-monospace,monospace;font-size:11px;font-weight:500;text-transform:uppercase;letter-spacing:.15em}",
  ".tk-article-price-table th:last-child,.tk-article-price-table td:last-child{text-align:right}",
  ".tk-article-price-table tbody tr+tr{border-top:1px solid rgba(30,42,35,.1)}",
  ".tk-article-price-table tbody th{color:var(--tk-tinta);font-size:14.5px;font-weight:500}",
  ".tk-article-price-table tbody td{color:var(--tk-cobre-dark);font-family:var(--font-plex-mono),ui-monospace,monospace;font-size:14px;font-weight:600}",
  ".tk-article-highlight{margin:1.5rem 0 0;padding:1rem 1.25rem;border:1px solid rgba(180,85,45,.3);border-radius:.5rem;background:rgba(180,85,45,.1);color:var(--tk-tinta);font-family:var(--font-fraunces),Georgia,serif;font-size:1.5rem;font-weight:600}",
  ".tk-article-cta{margin-top:5rem;padding:2.25rem;border-radius:.75rem;background:var(--tk-noche);color:var(--tk-crema)}",
  ".tk-article-cta-label{margin:0;color:var(--tk-cobre-light);font-family:var(--font-plex-mono),ui-monospace,monospace;font-size:11px;text-transform:uppercase;letter-spacing:.25em}",
  ".tk-article-cta-title{margin:1rem 0 0;font-family:var(--font-fraunces),Georgia,serif;font-size:1.875rem;font-weight:600;line-height:1.2}",
  ".tk-article-cta-title em{color:var(--tk-cobre-light)}",
  ".tk-article-cta-copy{max-width:520px;margin:1rem 0 0;color:rgba(244,240,230,.78);font-size:14.5px;line-height:1.7}",
  ".tk-article-cta-actions{display:flex;flex-wrap:wrap;align-items:center;gap:1rem;margin-top:1.75rem}",
  ".tk-editorial-button-copper{display:inline-block;padding:.875rem 1.75rem;border-radius:.375rem;background:var(--tk-cobre-dark);color:var(--tk-crema);font-size:14.5px;font-weight:600;transition:background-color .3s}",
  ".tk-editorial-button-copper:hover{background:var(--tk-cobre-dark)}",
  ".tk-article-register{color:var(--tk-crema);font-size:14px;font-weight:600}",
  ".tk-legal{margin-top:1.5rem}",
  ".tk-legal h2{margin:3rem 0 0;color:var(--tk-tinta);font-family:var(--font-fraunces),Georgia,serif;font-size:1.5rem;font-weight:600}",
  ".tk-legal h3{margin:1.75rem 0 0;color:var(--tk-tinta);font-size:15px;font-weight:600}",
  ".tk-legal p,.tk-legal li{margin:.75rem 0 0;color:var(--tk-ceniza);font-size:14.5px;line-height:1.7}",
  ".tk-legal ul{margin:.75rem 0 0;padding-left:1.25rem}",
  ".tk-legal li+li{margin-top:.375rem}",
  ".tk-legal strong{color:var(--tk-tinta);font-weight:600}",
  ".tk-legal a{color:var(--tk-cobre-dark);text-decoration:underline;text-underline-offset:2px}",
  ".tk-legal-price-wrap{margin-top:1rem;overflow:hidden;border:1px solid rgba(30,42,35,.15);border-radius:.5rem}",
  ".tk-legal-price-table{width:100%;border-collapse:collapse;text-align:left}",
  ".tk-legal-price-table thead{background:var(--tk-tinta);color:var(--tk-crema)}",
  ".tk-legal-price-table th,.tk-legal-price-table td{padding:.75rem 1rem}",
  ".tk-legal-price-table thead th{font-family:var(--font-plex-mono),ui-monospace,monospace;font-size:11px;font-weight:500;text-transform:uppercase;letter-spacing:.15em}",
  ".tk-legal-price-table th:last-child,.tk-legal-price-table td:last-child{text-align:right}",
  ".tk-legal-price-table tbody tr+tr{border-top:1px solid rgba(30,42,35,.1)}",
  ".tk-legal-price-table tbody th{color:var(--tk-ceniza);font-size:14.5px;font-weight:400}",
  ".tk-legal-price-table tbody td{color:var(--tk-tinta);font-family:var(--font-plex-mono),ui-monospace,monospace;font-size:13px;font-weight:600}",
  ".tk-legal-highlight{margin-top:1.5rem;padding:1rem 1.25rem;border:1px solid rgba(180,85,45,.25);border-radius:.5rem;background:rgba(180,85,45,.1)}",
  ".tk-legal-highlight p{margin:0;color:var(--tk-tinta);font-family:var(--font-fraunces),Georgia,serif;font-size:1.25rem;font-weight:600}",
  ".tk-legal-notice{margin-top:1.5rem;padding:1rem 1.25rem;border:1px solid rgba(180,85,45,.25);border-radius:.5rem;background:rgba(180,85,45,.1)}",
  ".tk-legal-notice p{margin:0;color:var(--tk-ceniza);font-size:14.5px;line-height:1.7}",
  "@media(min-width:640px){.tk-blog-card{padding:2.25rem}.tk-editorial-title,.tk-article-title{font-size:3rem}}",
  "@media(min-width:768px){.tk-editorial-main,.tk-article-main{padding-top:10rem;padding-left:2rem;padding-right:2rem}}",
].join("")
