export const homeStyles = [
  ".tk-home, .tk-home * { box-sizing: border-box; }\n",
  ".tk-home { min-height: 100vh; overflow-x: clip; background: #f4f0e6; color: #1e2a23; font-family: var(--font-archivo), system-ui, sans-serif; -webkit-font-smoothing: antialiased; text-rendering: optimizeLegibility; }\n",
  ".tk-home :where(h1, h2, h3, p, figure) { margin: 0; }\n",
  ".tk-home :where(a, button):focus-visible { outline: 3px solid #c96a42; outline-offset: 4px; }\n",
  ".tk-image-fluid { display: block; width: 100%; height: auto; }\n",
  ".tk-visually-hidden { position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0, 0, 0, 0); white-space: nowrap; border: 0; }\n",
  ".tk-section-shell { width: 100%; max-width: 1200px; margin-inline: auto; padding-inline: 1.25rem; }\n",
  ".tk-eyebrow { margin: 0; font-family: var(--font-plex-mono), ui-monospace, monospace; font-size: 11px; line-height: 1.5; letter-spacing: 0.25em; text-transform: uppercase; }\n",
  ".tk-eyebrow-light { color: #8f4020; }\n",
  ".tk-eyebrow-dark { color: #c96a42; }\n",
  ".tk-section-title { max-width: 42rem; margin-top: 1rem; font-family: var(--font-fraunces), Georgia, serif; font-size: 2.25rem; font-weight: 600; line-height: 1.25; letter-spacing: -0.02em; }\n",
  ".tk-section-title-light { color: #f4f0e6; }\n",
  ".tk-section-title-dark { color: #1e2a23; }\n",
  ".tk-button { display: inline-flex; min-height: 52px; align-items: center; justify-content: center; border: 1px solid transparent; border-radius: 0.375rem; padding: 0.875rem 1.75rem; font: inherit; font-size: 15px; font-weight: 600; line-height: 1.35; text-align: center; transition: color 300ms ease, background-color 300ms ease, border-color 300ms ease, transform 300ms ease; }\n",
  ".tk-button:hover { transform: translateY(-1px); }\n",
  ".tk-button-copper { background: #8f4020; color: #f4f0e6; }\n",
  ".tk-button-copper:hover { background: #1e2a23; }\n",
  ".tk-button-dark { background: #1e2a23; color: #f4f0e6; }\n",
  ".tk-button-dark:hover { background: #2c3a31; }\n",
  ".tk-button-outline-dark { border-color: rgba(30, 42, 35, 0.3); color: #1e2a23; }\n",
  ".tk-button-outline-dark:hover { border-color: #b4552d; color: #8f4020; }\n",
  ".tk-button-outline-light { border-color: rgba(244, 240, 230, 0.3); color: #f4f0e6; }\n",
  ".tk-button-outline-light:hover { border-color: #c96a42; color: #c96a42; }\n",
  ".tk-drawn-link { display: inline-block; background-image: linear-gradient(currentColor, currentColor); background-repeat: no-repeat; background-position: 0 100%; background-size: 0 1.5px; transition: background-size 500ms cubic-bezier(0.22, 1, 0.36, 1); }\n",
  ".tk-drawn-link:hover { background-size: 100% 1.5px; }\n",
  ".tk-frame { overflow: hidden; border: 1px solid rgba(30, 42, 35, 0.15); border-radius: 0.75rem; background: #131a16; box-shadow: 0 30px 80px -20px rgba(30, 42, 35, 0.35); }\n",
  ".tk-frame-bar { display: flex; align-items: center; gap: 0.375rem; min-width: 0; border-bottom: 1px solid rgba(255, 255, 255, 0.1); background: #1e2a23; padding: 0.625rem 1rem; }\n",
  ".tk-frame-dot { flex: 0 0 auto; width: 0.5rem; height: 0.5rem; border-radius: 999px; background: rgba(244, 240, 230, 0.2); }\n",
  ".tk-frame-url { min-width: 0; margin-left: 0.75rem; overflow: hidden; color: rgba(244, 240, 230, 0.55); font-family: var(--font-plex-mono), ui-monospace, monospace; font-size: 10px; letter-spacing: 0.025em; text-overflow: ellipsis; white-space: nowrap; }\n",
  ".tk-price-card { overflow: hidden; border: 1px solid rgba(30, 42, 35, 0.15); border-radius: 0.75rem; background: #f4f0e6; }\n",
  ".tk-price-header { border-bottom: 1px solid rgba(30, 42, 35, 0.15); background: #1e2a23; padding: 1.25rem 1.5rem; color: #f4f0e6; }\n",
  ".tk-price-title { font-family: var(--font-fraunces), Georgia, serif; font-size: 1.5rem; font-weight: 600; line-height: 1.25; }\n",
  ".tk-price-note { margin-top: 0.25rem; color: rgba(244, 240, 230, 0.7); font-size: 13px; line-height: 1.625; }\n",
  ".tk-price-table { width: 100%; border-collapse: collapse; }\n",
  ".tk-price-columns { background: #eae3d2; color: #5a554a; font-family: var(--font-plex-mono), ui-monospace, monospace; font-size: 10px; letter-spacing: 0.18em; text-transform: uppercase; }\n",
  ".tk-price-column-cabins, .tk-price-column-value { padding: 0.75rem 1.5rem; font-weight: 500; }\n",
  ".tk-price-column-cabins { text-align: left; }\n",
  ".tk-price-column-value { text-align: right; }\n",
  ".tk-price-body { color: inherit; }\n",
  ".tk-price-row + .tk-price-row { border-top: 1px solid rgba(30, 42, 35, 0.1); }\n",
  ".tk-price-cabins, .tk-price-value { padding: 1rem 1.5rem; }\n",
  ".tk-price-cabins { color: #5a554a; font-size: 14px; font-weight: 400; text-align: left; }\n",
  ".tk-price-value { color: #1e2a23; font-family: var(--font-plex-mono), ui-monospace, monospace; font-size: 15px; font-weight: 600; text-align: right; }\n",
  ".tk-hero { position: relative; overflow: hidden; padding-block: 7rem 5rem; background: #131a16; color: #f4f0e6; }\n",
  ".tk-hero-background { object-fit: cover; object-position: center; opacity: 0.7; }\n",
  ".tk-hero-overlay { position: absolute; inset: 0; background: linear-gradient(to right, rgba(19, 26, 22, 0.95), rgba(19, 26, 22, 0.7), rgba(19, 26, 22, 0.25)); }\n",
  ".tk-hero-fade { position: absolute; inset-inline: 0; bottom: 0; height: 10rem; background: linear-gradient(to top, #131a16, transparent); }\n",
  ".tk-hero-layout { position: relative; z-index: 1; display: grid; width: 100%; max-width: 1200px; margin-inline: auto; align-items: center; gap: 3rem; padding-inline: 1.25rem; }\n",
  ".tk-hero-copy, .tk-hero-product { min-width: 0; }\n",
  ".tk-hero-title { margin-top: 1.25rem; color: #f4f0e6; font-family: var(--font-fraunces), Georgia, serif; font-size: 44px; font-weight: 600; line-height: 1.02; letter-spacing: -0.025em; text-wrap: balance; }\n",
  ".tk-hero-title-accent { color: #c96a42; font-style: italic; }\n",
  ".tk-hero-lead { max-width: 28rem; margin-top: 1.5rem; color: rgba(244, 240, 230, 0.85); font-size: 16.5px; line-height: 1.625; }\n",
  ".tk-hero-actions { display: flex; flex-wrap: wrap; align-items: center; gap: 1rem; margin-top: 2.25rem; }\n",
  ".tk-hero-primary { box-shadow: 0 12px 40px -10px rgba(180, 85, 45, 0.7); }\n",
  ".tk-hero-secondary { color: #f4f0e6; font-size: 15px; font-weight: 500; }\n",
  ".tk-hero-proof { margin-top: 1.75rem; color: rgba(244, 240, 230, 0.7); font-family: var(--font-plex-mono), ui-monospace, monospace; font-size: 11.5px; line-height: 1.55; letter-spacing: 0.025em; }\n",
  ".tk-hero-product { position: relative; }\n",
  ".tk-hero-product-inner { position: relative; }\n",
  ".tk-booking-notice { position: absolute; bottom: -1.5rem; left: 1rem; width: min(280px, calc(100% - 2rem)); border: 1px solid rgba(30, 42, 35, 0.1); border-radius: 0.75rem; background: #f4f0e6; padding: 1rem; color: #1e2a23; box-shadow: 0 25px 60px -15px rgba(0, 0, 0, 0.7); }\n",
  ".tk-booking-notice-heading { display: flex; align-items: center; gap: 0.5rem; }\n",
  ".tk-booking-notice-icon { display: flex; width: 1.75rem; height: 1.75rem; flex: 0 0 1.75rem; align-items: center; justify-content: center; border-radius: 999px; background: rgba(37, 211, 102, 0.15); color: #168342; font-weight: 700; }\n",
  ".tk-booking-notice-label { color: #5a554a; font-family: var(--font-plex-mono), ui-monospace, monospace; font-size: 10px; letter-spacing: 0.15em; text-transform: uppercase; }\n",
  ".tk-booking-notice-title { margin-top: 0.5rem; font-size: 13px; font-weight: 500; line-height: 1.375; }\n",
  ".tk-booking-notice-detail { margin-top: 0.125rem; color: #5a554a; font-family: var(--font-plex-mono), ui-monospace, monospace; font-size: 11px; line-height: 1.625; }\n",
  ".tk-benefits-strip { background: #8f4020; }\n",
  ".tk-benefits-list { display: flex; width: 100%; max-width: 1200px; margin-inline: auto; flex-wrap: wrap; align-items: center; justify-content: center; column-gap: 2.5rem; row-gap: 0.5rem; padding: 1.25rem; }\n",
  ".tk-benefit-item { color: #f4f0e6; font-family: var(--font-plex-mono), ui-monospace, monospace; font-size: 11.5px; letter-spacing: 0.18em; text-align: center; text-transform: uppercase; }\n",
  ".tk-problem { width: 100%; max-width: 1200px; margin-inline: auto; padding: 6rem 1.25rem; scroll-margin-top: 4rem; }\n",
  ".tk-problem-layout { display: grid; align-items: center; gap: 3rem; }\n",
  ".tk-problem-title { margin-top: 1.5rem; color: #1e2a23; font-family: var(--font-fraunces), Georgia, serif; font-size: 1.875rem; font-weight: 500; line-height: 1.2; letter-spacing: -0.015em; text-wrap: balance; }\n",
  ".tk-problem-text { max-width: 32rem; margin-top: 2rem; color: #5a554a; font-size: 16px; line-height: 1.625; }\n",
  ".tk-problem-figure { margin: 0; }\n",
  ".tk-problem-image { display: block; width: 100%; height: auto; border: 1px solid rgba(30, 42, 35, 0.1); border-radius: 0.75rem; box-shadow: 0 30px 70px -25px rgba(30, 42, 35, 0.5); }\n",
  ".tk-problem-caption { margin-top: 0.75rem; color: #5a554a; font-family: var(--font-plex-mono), ui-monospace, monospace; font-size: 11px; letter-spacing: 0.18em; text-transform: uppercase; }\n",
  ".tk-process { padding-block: 6rem; scroll-margin-top: 4rem; background: #131a16; color: #f4f0e6; }\n",
  ".tk-process-grid { display: grid; gap: 1.25rem; margin-top: 3.5rem; }\n",
  ".tk-process-card { height: 100%; border: 1px solid rgba(244, 240, 230, 0.15); border-radius: 0.75rem; background: #131a16; padding: 1.75rem; }\n",
  ".tk-process-number { color: #c96a42; font-family: var(--font-plex-mono), ui-monospace, monospace; font-size: 12px; }\n",
  ".tk-process-title { margin-top: 1rem; font-family: var(--font-fraunces), Georgia, serif; font-size: 1.5rem; font-weight: 600; line-height: 1.25; }\n",
  ".tk-process-text { margin-top: 0.75rem; color: rgba(244, 240, 230, 0.7); font-size: 14.5px; line-height: 1.625; }\n",
  ".tk-process-product { margin-top: 3rem; }\n",
  ".tk-cases { width: 100%; max-width: 1200px; margin-inline: auto; padding: 6rem 1.25rem; scroll-margin-top: 4rem; }\n",
  ".tk-cases-heading { display: flex; flex-wrap: wrap; align-items: flex-end; justify-content: space-between; gap: 1.5rem; }\n",
  ".tk-cases .tk-section-title { max-width: 36rem; }\n",
  ".tk-cases-intro { max-width: 24rem; color: #5a554a; font-size: 14.5px; line-height: 1.625; }\n",
  ".tk-cases-grid { display: grid; gap: 1.5rem; margin-top: 3rem; }\n",
  ".tk-case-link { display: block; }\n",
  ".tk-case-image-wrap { overflow: hidden; aspect-ratio: 16 / 11; }\n",
  ".tk-case-image { display: block; width: 100%; height: 100%; object-fit: cover; object-position: top; transition: transform 700ms cubic-bezier(0.22, 1, 0.36, 1); }\n",
  ".tk-case-link:hover .tk-case-image { transform: scale(1.02); }\n",
  ".tk-case-title { margin-top: 1.25rem; color: #1e2a23; font-family: var(--font-fraunces), Georgia, serif; font-size: 1.25rem; font-weight: 600; line-height: 1.35; }\n",
  ".tk-case-place { margin-top: 0.25rem; color: #8f4020; font-family: var(--font-plex-mono), ui-monospace, monospace; font-size: 11px; letter-spacing: 0.15em; text-transform: uppercase; }\n",
  ".tk-case-description { margin-top: 0.5rem; color: #5a554a; font-size: 13.5px; line-height: 1.625; }\n",
  ".tk-case-action { margin-top: 0.75rem; color: #1e2a23; font-size: 13.5px; font-weight: 600; }\n",
  ".tk-features { padding-block: 6rem; scroll-margin-top: 4rem; background: #1e2a23; color: #f4f0e6; }\n",
  ".tk-features-grid { display: grid; gap: 1.25rem; margin-top: 3rem; }\n",
  ".tk-feature-card { height: 100%; border: 1px solid rgba(244, 240, 230, 0.1); border-radius: 0.75rem; background: #131a16; padding: 1.5rem; }\n",
  ".tk-feature-number { color: #c96a42; font-family: var(--font-plex-mono), ui-monospace, monospace; font-size: 12px; }\n",
  ".tk-feature-title { margin-top: 0.75rem; font-family: var(--font-fraunces), Georgia, serif; font-size: 1.25rem; font-weight: 600; line-height: 1.35; }\n",
  ".tk-feature-text { margin-top: 0.5rem; color: rgba(244, 240, 230, 0.7); font-size: 13.5px; line-height: 1.625; }\n",
  ".tk-pricing { width: 100%; max-width: 1200px; margin-inline: auto; padding: 6rem 1.25rem; scroll-margin-top: 4rem; }\n",
  ".tk-pricing-heading { max-width: 48rem; margin-inline: auto; text-align: center; }\n",
  ".tk-pricing-title { margin-top: 1rem; color: #1e2a23; font-family: var(--font-fraunces), Georgia, serif; font-size: 2.25rem; font-weight: 600; line-height: 1.25; letter-spacing: -0.02em; text-wrap: balance; }\n",
  ".tk-pricing-intro { max-width: 42rem; margin: 1.5rem auto 0; color: #5a554a; font-size: 15.5px; line-height: 1.625; }\n",
  ".tk-pricing-grid { display: grid; gap: 1.5rem; margin-top: 3rem; }\n",
  ".tk-season-highlight { margin-top: 2rem; border-radius: 0.75rem; background: #8f4020; padding: 2rem 1.5rem; color: #f4f0e6; text-align: center; }\n",
  ".tk-season-title { font-family: var(--font-fraunces), Georgia, serif; font-size: 1.875rem; font-weight: 600; line-height: 1.25; }\n",
  ".tk-season-text { max-width: 36rem; margin: 0.75rem auto 0; color: rgba(244, 240, 230, 0.85); font-size: 14.5px; line-height: 1.625; }\n",
  ".tk-pricing-actions { display: flex; flex-wrap: wrap; align-items: center; justify-content: center; gap: 1rem; margin-top: 2.5rem; }\n",
  ".tk-faq { border-top: 1px solid rgba(30, 42, 35, 0.1); scroll-margin-top: 4rem; }\n",
  ".tk-faq-layout { display: grid; width: 100%; max-width: 1200px; margin-inline: auto; gap: 3rem; padding: 6rem 1.25rem; }\n",
  ".tk-faq-title { margin-top: 1rem; color: #1e2a23; font-family: var(--font-fraunces), Georgia, serif; font-size: 2.25rem; font-weight: 600; line-height: 1.25; letter-spacing: -0.02em; }\n",
  ".tk-faq-intro { margin-top: 1.5rem; color: #5a554a; font-size: 14.5px; line-height: 1.625; }\n",
  ".tk-faq-action { margin-top: 1rem; color: #8f4020; font-size: 15px; font-weight: 600; }\n",
  ".tk-final-cta { background: #131a16; color: #f4f0e6; }\n",
  ".tk-final-layout { display: grid; width: 100%; max-width: 1200px; margin-inline: auto; }\n",
  ".tk-final-copy { display: flex; flex-direction: column; justify-content: center; padding: 6rem 1.25rem; }\n",
  ".tk-final-mark { display: block; width: auto; height: 3rem; opacity: 0.9; }\n",
  ".tk-final-title { margin-top: 2rem; font-family: var(--font-fraunces), Georgia, serif; font-size: 2.25rem; font-weight: 600; line-height: 1.25; letter-spacing: -0.02em; text-wrap: balance; }\n",
  ".tk-final-title-accent { color: #c96a42; font-style: italic; }\n",
  ".tk-final-text { max-width: 28rem; margin-top: 1.5rem; color: rgba(244, 240, 230, 0.7); font-size: 15.5px; line-height: 1.625; }\n",
  ".tk-final-actions { display: flex; flex-wrap: wrap; gap: 1rem; margin-top: 2.5rem; }\n",
  ".tk-final-button { padding-inline: 2rem; font-size: 15.5px; }\n",
  ".tk-final-visual { position: relative; min-height: 340px; overflow: hidden; }\n",
  ".tk-final-image { object-fit: cover; }\n",
  ".tk-final-overlay { position: absolute; inset: 0; background: linear-gradient(to right, #131a16, rgba(19, 26, 22, 0.3), transparent); }\n",
  "@media (min-width: 640px) {\n",
  "  .tk-hero-title { font-size: 3.75rem; }\n",
  "  .tk-booking-notice { left: 2rem; }\n",
  "  .tk-problem-title { font-size: 2.25rem; }\n",
  "  .tk-section-title, .tk-pricing-title { font-size: 3rem; }\n",
  "  .tk-season-highlight { padding-inline: 2.5rem; }\n",
  "  .tk-season-title { font-size: 2.25rem; }\n",
  "  .tk-final-title { font-size: 3rem; }\n",
  "}\n",
  "@media (min-width: 768px) {\n",
  "  .tk-section-shell { padding-inline: 2rem; }\n",
  "  .tk-hero { padding-block: 10rem 7rem; }\n",
  "  .tk-hero-layout { grid-template-columns: repeat(12, minmax(0, 1fr)); padding-inline: 2rem; }\n",
  "  .tk-hero-copy, .tk-hero-product { grid-column: span 6 / span 6; }\n",
  "  .tk-hero-product-inner { margin-right: -2.5rem; }\n",
  "  .tk-benefits-list { justify-content: space-between; padding-inline: 2rem; }\n",
  "  .tk-problem, .tk-cases, .tk-pricing { padding: 9rem 2rem; }\n",
  "  .tk-problem-layout { grid-template-columns: repeat(12, minmax(0, 1fr)); }\n",
  "  .tk-problem-copy { grid-column: span 7 / span 7; }\n",
  "  .tk-problem-visual { grid-column: span 5 / span 5; }\n",
  "  .tk-problem-figure { margin-right: -1.5rem; }\n",
  "  .tk-process, .tk-features { padding-block: 8rem; }\n",
  "  .tk-process-grid, .tk-cases-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); }\n",
  "  .tk-features-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }\n",
  "  .tk-faq-layout { padding: 8rem 2rem; }\n",
  "  .tk-final-layout { grid-template-columns: repeat(2, minmax(0, 1fr)); }\n",
  "  .tk-final-copy { padding: 9rem 2rem; }\n",
  "  .tk-final-visual { min-height: 0; }\n",
  "}\n",
  "@media (min-width: 1024px) {\n",
  "  .tk-hero-title { font-size: 4.5rem; }\n",
  "  .tk-hero-product-inner { margin-right: -4rem; }\n",
  "  .tk-problem-title { font-size: 42px; }\n",
  "  .tk-problem-figure { margin-right: -2.5rem; }\n",
  "  .tk-features-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); }\n",
  "  .tk-pricing-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); }\n",
  "  .tk-faq-layout { grid-template-columns: 1fr 1.6fr; gap: 5rem; }\n",
  "  .tk-faq-heading { position: sticky; top: 6rem; align-self: start; }\n",
  "  .tk-final-title { font-size: 3.75rem; }\n",
  "}\n",
  "@media (max-width: 639px) {\n",
  "  .tk-hero-actions, .tk-pricing-actions, .tk-final-actions { align-items: stretch; }\n",
  "  .tk-hero-actions .tk-button, .tk-pricing-actions .tk-button, .tk-final-actions .tk-button { width: 100%; }\n",
  "  .tk-hero-secondary { padding-block: 0.5rem; text-align: center; }\n",
  "  .tk-price-column-cabins, .tk-price-column-value, .tk-price-cabins, .tk-price-value { padding-inline: 1rem; }\n",
  "  .tk-final-overlay { background: linear-gradient(to bottom, transparent, rgba(19, 26, 22, 0.45)); }\n",
  "}\n",
  "@media (prefers-reduced-motion: reduce) {\n",
  "  .tk-button, .tk-drawn-link, .tk-case-image { transition: none; }\n",
  "  .tk-button:hover, .tk-case-link:hover .tk-case-image { transform: none; }\n",
  "}\n",
  "@media (prefers-contrast: more) {\n",
  "  .tk-hero-lead, .tk-hero-proof, .tk-price-note, .tk-process-text, .tk-feature-text, .tk-season-text, .tk-final-text { color: #f4f0e6; }\n",
  "  .tk-problem-text, .tk-problem-caption, .tk-cases-intro, .tk-case-description, .tk-pricing-intro, .tk-faq-intro, .tk-price-cabins { color: #1e2a23; }\n",
  "  .tk-drawn-link { background-size: 100% 2px; }\n",
  "  .tk-frame, .tk-price-card, .tk-problem-image, .tk-process-card, .tk-feature-card { border-width: 2px; }\n",
  "}\n",
].join("")

export default homeStyles
