export const SHELL_STYLES = [
  ".tk-skip-link{position:fixed;left:1rem;top:.75rem;z-index:100;transform:translateY(-6rem);border:2px solid var(--tk-cobre-dark);border-radius:.375rem;background:var(--tk-noche);padding:.75rem 1rem;color:var(--tk-crema);font-size:.875rem;font-weight:600;box-shadow:0 20px 25px -5px rgba(19,26,22,.25);transition:transform .3s var(--tk-ease)}",
  ".tk-skip-link:focus-visible{transform:translateY(0)}",
  ".tk-site-header{position:fixed;inset:0 0 auto;z-index:50;border-bottom:1px solid transparent;background:transparent;transition:background-color .5s var(--tk-ease),border-color .5s var(--tk-ease),box-shadow .5s var(--tk-ease)}",
  ".tk-site-header[data-elevated=true]{border-color:rgba(30,42,35,.1);background:rgba(244,240,230,.92);box-shadow:0 8px 30px rgba(19,26,22,.04);-webkit-backdrop-filter:blur(12px);backdrop-filter:blur(12px)}",
  ".tk-site-nav{display:flex;align-items:center;justify-content:space-between;width:100%;max-width:1200px;height:4rem;margin:0 auto;padding:0 1.25rem}",
  ".tk-brand-link{display:flex;align-items:center;gap:.625rem;border-radius:.25rem}",
  ".tk-brand-mark{width:auto;height:2rem;transition:filter .5s var(--tk-ease)}",
  ".tk-brand-mark[data-tone=dark]{filter:brightness(0) saturate(100%) invert(40%) sepia(57%) saturate(1244%) hue-rotate(337deg) brightness(88%) contrast(87%)}",
  ".tk-brand-name{font-family:var(--font-fraunces),Georgia,serif;font-size:1.25rem;font-weight:600;letter-spacing:.25em;transition:color .5s var(--tk-ease)}",
  ".tk-brand-name[data-tone=dark]{color:var(--tk-tinta)}",
  ".tk-brand-name[data-tone=light]{color:var(--tk-crema)}",
  ".tk-desktop-nav{display:none;align-items:center;gap:1.75rem}",
  ".tk-nav-link{position:relative;padding:.35rem 0;background-image:linear-gradient(currentColor,currentColor);background-repeat:no-repeat;background-position:0 100%;background-size:0 1.5px;font-size:13.5px;transition:color .25s ease,background-size .5s var(--tk-ease)}",
  ".tk-nav-link:hover{background-size:100% 1.5px}",
  ".tk-nav-link[data-tone=dark]{color:var(--tk-ceniza)}",
  ".tk-nav-link[data-tone=dark]:hover{color:var(--tk-tinta)}",
  ".tk-nav-link[data-tone=light]{color:rgba(244,240,230,.8)}",
  ".tk-nav-link[data-tone=light]:hover{color:var(--tk-crema)}",
  ".tk-nav-cta,.tk-mobile-cta,.tk-not-found-primary{display:inline-flex;align-items:center;justify-content:center;border-radius:.375rem;background:var(--tk-cobre-dark);color:var(--tk-crema);font-weight:600;transition:background-color .3s ease,transform .3s var(--tk-ease)}",
  ".tk-nav-cta{padding:.625rem 1.25rem;font-size:13.5px}",
  ".tk-nav-cta:hover,.tk-mobile-cta:hover,.tk-not-found-primary:hover{background:var(--tk-tinta)}",
  ".tk-menu-button{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:5px;width:2.5rem;height:2.5rem;margin:0;padding:0;border:0;border-radius:.375rem;background:transparent;cursor:pointer}",
  ".tk-menu-line{display:block;width:1.5rem;height:2px;background:var(--tk-crema);transition:background-color .3s ease,opacity .3s ease,transform .3s var(--tk-ease)}",
  ".tk-menu-line[data-tone=dark]{background:var(--tk-tinta)}",
  ".tk-menu-line[data-position=top][data-open=true]{transform:translateY(7px) rotate(45deg)}",
  ".tk-menu-line[data-position=middle][data-open=true]{opacity:0}",
  ".tk-menu-line[data-position=bottom][data-open=true]{transform:translateY(-7px) rotate(-45deg)}",
  ".tk-mobile-menu{position:fixed;inset:4rem 0 0;z-index:40;display:flex;visibility:hidden;pointer-events:none;flex-direction:column;overflow-y:auto;background:var(--tk-crema);padding:2rem 1.5rem 2.5rem;opacity:0;transition:visibility .5s var(--tk-ease),opacity .5s var(--tk-ease)}",
  ".tk-mobile-menu[data-open=true]{visibility:visible;pointer-events:auto;opacity:1}",
  ".tk-mobile-links{display:flex;flex-direction:column;border-top:1px solid rgba(30,42,35,.15)}",
  ".tk-mobile-link{transform:translateY(.75rem);border-bottom:1px solid rgba(30,42,35,.15);padding:1rem 0;color:var(--tk-tinta);font-family:var(--font-fraunces),Georgia,serif;font-size:1.875rem;line-height:1.15;opacity:0;transition:transform .5s var(--tk-ease),opacity .5s var(--tk-ease),color .2s ease}",
  ".tk-mobile-link[data-open=true]{transform:translateY(0);opacity:1}",
  ".tk-mobile-link:hover{color:var(--tk-cobre-dark)}",
  ".tk-mobile-cta{margin-top:2rem;padding:1rem 1.5rem;font-size:1rem;text-align:center}",
  ".tk-mobile-note{margin:1.5rem 0 0;color:var(--tk-ceniza);font-family:var(--font-plex-mono),ui-monospace,monospace;font-size:11px;line-height:1.55;letter-spacing:.025em;text-align:center}",
  ".tk-footer{background:var(--tk-noche);color:var(--tk-crema)}",
  ".tk-footer-wrap{width:100%;max-width:1200px;margin:0 auto;padding:4rem 1.25rem}",
  ".tk-footer-about,.tk-footer-nav,.tk-not-found-copy{min-width:0}",
  ".tk-footer-grid{display:grid;gap:3rem}",
  ".tk-footer-brand{display:flex;align-items:center;gap:.75rem}",
  ".tk-footer-mark{width:auto;height:2.25rem}",
  ".tk-footer-name{font-family:var(--font-fraunces),Georgia,serif;font-size:1.5rem;font-weight:600;letter-spacing:.25em}",
  ".tk-footer-description{max-width:20rem;margin:1rem 0 0;color:rgba(244,240,230,.72);font-size:13.5px;line-height:1.625}",
  ".tk-footer-origin{margin:1rem 0 0;color:var(--tk-cobre-light);font-family:var(--font-plex-mono),ui-monospace,monospace;font-size:11px;letter-spacing:.2em;text-transform:uppercase}",
  ".tk-footer-heading{margin:0;color:rgba(244,240,230,.72);font-family:var(--font-plex-mono),ui-monospace,monospace;font-size:10px;letter-spacing:.25em;text-transform:uppercase}",
  ".tk-footer-list{display:flex;flex-direction:column;gap:.625rem;margin:1rem 0 0;padding:0;list-style:none;font-size:13.5px}",
  ".tk-footer-link{display:inline;background-image:linear-gradient(currentColor,currentColor);background-repeat:no-repeat;background-position:0 100%;background-size:0 1.5px;color:rgba(244,240,230,.82);overflow-wrap:anywhere;transition:color .25s ease,background-size .5s var(--tk-ease)}",
  ".tk-footer-link:hover{background-size:100% 1.5px;color:var(--tk-crema)}",
  ".tk-footer-bottom{display:flex;flex-direction:column;align-items:center;justify-content:space-between;gap:1rem;margin-top:3.5rem;border-top:1px solid rgba(244,240,230,.15);padding-top:1.75rem;color:rgba(244,240,230,.72);font-size:12.5px;text-align:center}",
  ".tk-footer-bottom p{margin:0}",
  ".tk-footer-audience{font-family:var(--font-plex-mono),ui-monospace,monospace;font-size:11px;letter-spacing:.025em}",
  ".tk-faq-list{border-top:1px solid rgba(30,42,35,.15)}",
  ".tk-faq-item{border-bottom:1px solid rgba(30,42,35,.15)}",
  ".tk-faq-question{margin:0}",
  ".tk-faq-button{display:flex;align-items:flex-start;justify-content:space-between;gap:1.25rem;width:100%;margin:0;border:0;border-radius:.25rem;background:transparent;padding:1.25rem 0;text-align:left;cursor:pointer}",
  ".tk-faq-label{color:var(--tk-tinta);font-size:1rem;font-weight:500;line-height:1.375}",
  ".tk-faq-icon{flex:0 0 auto;margin-top:.125rem;color:var(--tk-cobre-dark);font-family:var(--font-plex-mono),ui-monospace,monospace;font-size:1.25rem;line-height:1;transition:transform .3s var(--tk-ease)}",
  ".tk-faq-icon[data-open=true]{transform:rotate(45deg)}",
  ".tk-faq-answer{display:grid;grid-template-rows:0fr;opacity:0;transition:grid-template-rows .5s var(--tk-ease),opacity .5s var(--tk-ease)}",
  ".tk-faq-answer[data-open=true]{grid-template-rows:1fr;opacity:1}",
  ".tk-faq-answer-clip{overflow:hidden}",
  ".tk-faq-answer-copy{max-width:36rem;margin:0;padding:0 0 1.5rem;color:var(--tk-ceniza);font-size:14.5px;line-height:1.625}",
  ".tk-whatsapp-fab{position:fixed;right:1.5rem;bottom:max(1.5rem,env(safe-area-inset-bottom));z-index:40;display:flex;visibility:hidden;pointer-events:none;align-items:center;gap:0;transform:translateY(1rem);border-radius:9999px;background:var(--tk-wa);padding:.875rem;color:var(--tk-noche);box-shadow:0 10px 30px -8px rgba(37,211,102,.6);opacity:0;transition:visibility .5s var(--tk-ease),opacity .5s var(--tk-ease),transform .5s var(--tk-ease),gap .5s var(--tk-ease),padding-right .5s var(--tk-ease)}",
  ".tk-whatsapp-fab[data-visible=true]{visibility:visible;pointer-events:auto;transform:translateY(0);opacity:1}",
  ".tk-whatsapp-fab:hover,.tk-whatsapp-fab:focus-visible{gap:.5rem;padding-right:1.25rem}",
  ".tk-whatsapp-icon{display:block;flex:0 0 auto}",
  ".tk-whatsapp-label{max-width:0;overflow:hidden;font-size:13px;font-weight:600;white-space:nowrap;transition:max-width .5s var(--tk-ease)}",
  ".tk-whatsapp-fab:hover .tk-whatsapp-label,.tk-whatsapp-fab:focus-visible .tk-whatsapp-label{max-width:8.75rem}",
  ".tk-reveal{transform:translateY(26px);opacity:0;transition:opacity .8s var(--tk-ease),transform .8s var(--tk-ease)}",
  ".tk-reveal.tk-reveal--visible{transform:none;opacity:1}",
  ".tk-reveal--span-seven,.tk-reveal--span-five{min-width:0}",
  ".tk-reveal--spaced{margin-top:3rem}",
  ".tk-not-found-page{display:flex;min-height:100vh;flex-direction:column;background:var(--tk-crema)}",
  ".tk-not-found-main{display:flex;flex:1;align-items:center;width:100%;max-width:1200px;margin:0 auto;padding:8rem 1.25rem 6rem}",
  ".tk-not-found-grid{display:grid;align-items:center;width:100%;gap:2.5rem}",
  ".tk-not-found-code{margin:0;color:rgba(180,85,45,.2);font-family:var(--font-fraunces),Georgia,serif;font-size:8rem;font-weight:600;line-height:1}",
  ".tk-not-found-kicker{margin:0;color:var(--tk-cobre-dark);font-family:var(--font-plex-mono),ui-monospace,monospace;font-size:11px;letter-spacing:.22em;text-transform:uppercase}",
  ".tk-not-found-title{max-width:36rem;margin:1rem 0 0;color:var(--tk-tinta);font-family:var(--font-fraunces),Georgia,serif;font-size:2.25rem;font-weight:600;line-height:1.25}",
  ".tk-not-found-description{max-width:32rem;margin:1.25rem 0 0;color:var(--tk-ceniza);font-size:15.5px;line-height:1.625}",
  ".tk-not-found-actions{display:flex;flex-direction:column;gap:.75rem;margin-top:2rem}",
  ".tk-not-found-primary,.tk-not-found-secondary{padding:.875rem 1.5rem;font-size:.875rem;text-align:center}",
  ".tk-not-found-secondary{display:inline-flex;align-items:center;justify-content:center;border:1px solid rgba(30,42,35,.2);border-radius:.375rem;color:var(--tk-tinta);font-weight:600;transition:background-color .3s ease,border-color .3s ease}",
  ".tk-not-found-secondary:hover{border-color:rgba(30,42,35,.4);background:var(--tk-crema-deep)}",
  "@media(min-width:640px){.tk-footer-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.tk-footer-bottom{flex-direction:row;text-align:left}.tk-not-found-code{font-size:11rem}.tk-not-found-title{font-size:3rem}.tk-not-found-actions{flex-direction:row}}",
  "@media(min-width:768px){.tk-site-nav,.tk-footer-wrap{padding-left:2rem;padding-right:2rem}.tk-not-found-main{padding:10rem 2rem 8rem}.tk-not-found-grid{grid-template-columns:.75fr 1.25fr;gap:4rem}.tk-not-found-code{font-size:13rem}.tk-reveal--span-seven{grid-column:span 7/span 7}.tk-reveal--span-five{grid-column:span 5/span 5}}",
  "@media(min-width:1024px){.tk-desktop-nav{display:flex}.tk-menu-button,.tk-mobile-menu{display:none}.tk-footer-grid{grid-template-columns:1.4fr 1fr 1fr 1fr}}",
  "@media(prefers-reduced-motion:reduce){.tk-reveal{transform:none;opacity:1;transition:none}.tk-mobile-link{transform:none}}",
  "@media(prefers-contrast:more){.tk-site-header[data-elevated=true]{border-color:var(--tk-tinta);background:var(--tk-crema)}.tk-mobile-links,.tk-mobile-link,.tk-faq-list,.tk-faq-item{border-color:var(--tk-tinta)}.tk-nav-link[data-tone=light],.tk-footer-description,.tk-footer-heading,.tk-footer-link,.tk-footer-bottom{color:var(--tk-crema)}.tk-footer-bottom{border-color:var(--tk-crema)}}",
  "@media(forced-colors:active){.tk-brand-mark[data-tone=dark]{filter:none}.tk-skip-link{border:2px solid ButtonText}.tk-site-header[data-elevated=true]{border-bottom:1px solid CanvasText}.tk-whatsapp-fab{border:1px solid ButtonText}}",
].join("")
